name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build for Linux
      run: cargo build --release --verbose --target x86_64-unknown-linux-gnu
      if: matrix.os == 'linux'

    - name: Build for Windows
      run: cargo build --release --verbose --target x86_64-pc-windows-msvc
      if: matrix.os == 'windows'

    - name: Build for macOS
      run: cargo build --release --verbose --target x86_64-apple-darwin
      if: matrix.os == 'macos'

    - name: Run tests
      run: cargo test --verbose

    strategy:
      matrix:
        os: [linux, windows, macos]
